### ISSUE TITLE
ERROR about interactive_gui.py

### ISSUE THREAD

**Issue by lixixin** [hkchengrex/MiVOS#16]
Traceback (most recent call last):
  File "interactive_gui.py", line 34, in <module>
    from interact.fbrs_controller import FBRSController
  File "D:\Code\Pytorch\MiVOS-main\interact\fbrs_controller.py", line 2, in <module>
    from fbrs.controller import InteractiveController
  File "D:\Code\Pytorch\MiVOS-main\fbrs\controller.py", line 6, in <module>
    from fbrs.inference.predictors import get_predictor
  File "D:\Code\Pytorch\MiVOS-main\fbrs\inference\predictors\__init__.py", line 2, in <module>
    from .brs import InputBRSPredictor, FeatureBRSPredictor, HRNetFeatureBRSPredictor
  File "D:\Code\Pytorch\MiVOS-main\fbrs\inference\predictors\brs.py", line 7, in <module>
    from fbrs.model.is_hrnet_model import DistMapsHRNetModel
  File "D:\Code\Pytorch\MiVOS-main\fbrs\model\is_hrnet_model.py", line 4, in <module>
    from fbrs.model.ops import DistMaps
  File "D:\Code\Pytorch\MiVOS-main\fbrs\model\ops.py", line 6, in <module>
    from fbrs.utils.cython import get_dist_maps
  File "D:\Code\Pytorch\MiVOS-main\fbrs\utils\cython\__init__.py", line 2, in <module>
    from .dist_maps import get_dist_maps
  File "D:\Code\Pytorch\MiVOS-main\fbrs\utils\cython\dist_maps.py", line 3, in <module>
    from ._get_dist_maps import get_dist_maps
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\pyximport\pyximport.py", line 462, in load_module
    language_level=self.language_level)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\pyximport\pyximport.py", line 231, in load_module
    raise exc.with_traceback(tb)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\pyximport\pyximport.py", line 215, in load_module
    inplace=build_inplace, language_level=language_level)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\pyximport\pyximport.py", line 191, in build_module
    reload_support=pyxargs.reload_support)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\pyximport\pyxbuild.py", line 102, in pyx_to_dll
    dist.run_commands()
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\site-packages\Cython\Distutils\old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\command\build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\command\build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\_msvccompiler.py", line 345, in compile
    self.initialize()
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\_msvccompiler.py", line 238, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "D:\Softwares\Anaconda\envs\pytorch_17\lib\distutils\_msvccompiler.py", line 134, in _get_vc_env
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module fbrs.utils.cython._get_dist_maps failed: ['distutils.errors.DistutilsPlatformError: Unable to find vcvarsall.bat\n']

**Comment by hkchengrex** [comment]
Seems like you cannot import fbrs on your windows platform.
Not an expert in windows configuration but you might need to install/reinstall visual studio for their MSVC compiler to compile that python package.
