### ISSUE TITLE
Getting "ValueError: Davis root folder must be named "DAVIS" Error when i try run eval_interactive_davis.py

### ISSUE THREAD

**Issue by be-redAsmara** [hkchengrex/MiVOS#18]
Getting "ValueError: Davis root folder must be named "DAVIS" Error when i try run eval_interactive_davis.py

Traceback (most recent call last):
  File "/home/bereket/Desktop/IRCAD-Data/MiVOS/MiVOS-MiVOS-STCN/eval_interactive_davis.py", line 76, in <module>
    with DavisInteractiveSession(davis_root=davis_path+'/trainval', report_save_dir='../output', max_nb_interactions=8, max_time=8*30) as sess:
  File "/home/bereket/anaconda3/envs/ivos/lib/python3.9/site-packages/davisinteractive/session/session.py", line 89, in __enter__
    samples, max_t, max_i = self.connector.start_session(
  File "/home/bereket/anaconda3/envs/ivos/lib/python3.9/site-packages/davisinteractive/connector/local.py", line 29, in start_session
    self.service = EvaluationService(davis_root=davis_root)
  File "/home/bereket/anaconda3/envs/ivos/lib/python3.9/site-packages/davisinteractive/evaluation/service.py", line 27, in __init__
    self.davis = Davis(davis_root=davis_root)
  File "/home/bereket/anaconda3/envs/ivos/lib/python3.9/site-packages/davisinteractive/dataset/davis.py", line 93, in __init__
    raise ValueError('Davis root folder must be named "DAVIS"')
ValueError: Davis root folder must be named "DAVIS"

**Comment by hkchengrex** [comment]
You are probably using a different version of davis interactive. Install this: https://github.com/albertomontesg/davis-interactive

**Comment by be-redAsmara** [comment]
I am using the 1.0.4 version which is the same as the link you shared. Maybe you can create .yml file for the libraries you are using.

**Comment by hkchengrex** [comment]
This issue has been covered and fixed here: https://github.com/albertomontesg/davis-interactive/issues/31
I don't think that line in your stack trace still even exists anymore.

**Comment by be-redAsmara** [comment]
Thank you for the support. And really nice work.
