### ISSUE TITLE
ModuleNotFoundError: No module named 'pyximport'

### ISSUE THREAD

**Issue by RahulBhalley** [hkchengrex/MiVOS#38]
Hi @hkchengrex,

I'm trying to run the following command.

```bash
python interactive_gui.py --video example/example.mp4
```

But I get the following error.

```
codeboy@192 MiVOS % python interactive_gui.py --video example/example.mp4
Traceback (most recent call last):
  File "/Users/codeboy/MiVOS/interactive_gui.py", line 31, in <module>
    from interact.fbrs_controller import FBRSController
  File "/Users/codeboy/MiVOS/interact/fbrs_controller.py", line 2, in <module>
    from fbrs.controller import InteractiveController
  File "/Users/codeboy/MiVOS/fbrs/controller.py", line 6, in <module>
    from fbrs.inference.predictors import get_predictor
  File "/Users/codeboy/MiVOS/fbrs/inference/predictors/__init__.py", line 2, in <module>
    from .brs import InputBRSPredictor, FeatureBRSPredictor, HRNetFeatureBRSPredictor
  File "/Users/codeboy/MiVOS/fbrs/inference/predictors/brs.py", line 7, in <module>
    from fbrs.model.is_hrnet_model import DistMapsHRNetModel
  File "/Users/codeboy/MiVOS/fbrs/model/is_hrnet_model.py", line 4, in <module>
    from fbrs.model.ops import DistMaps
  File "/Users/codeboy/MiVOS/fbrs/model/ops.py", line 6, in <module>
    from fbrs.utils.cython import get_dist_maps
  File "/Users/codeboy/MiVOS/fbrs/utils/cython/__init__.py", line 2, in <module>
    from .dist_maps import get_dist_maps
  File "/Users/codeboy/MiVOS/fbrs/utils/cython/dist_maps.py", line 1, in <module>
    import pyximport; pyximport.install(pyximport=True, language_level=3)
ModuleNotFoundError: No module named 'pyximport'
```

How can this be fixed?

Regards
Rahul Bhalley

**Comment by hkchengrex** [comment]
Can you try this? https://stackoverflow.com/questions/33221945/where-is-pyximport

**Comment by RahulBhalley** [comment]
Thanks.
